# Generated by Django 2.2 on 2019-05-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informator', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(height_field='height', upload_to='gallery_pics', width_field='width'),
        ),
    ]
