# Generated by Django 2.2 on 2019-05-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powiadomienia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powiadomienie',
            name='typPowiadomienia',
            field=models.CharField(choices=[(0, 'testowe'), (1, 'rodzaj 1'), (2, 'rodzaj 2')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
