# Generated by Django 2.2 on 2019-05-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powiadomienia', '0003_auto_20190504_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powiadomienie',
            name='typPowiadomienia',
            field=models.CharField(choices=[('0', 'testowe'), ('1', 'rodzaj 1'), ('2', 'rodzaj 2')], default='0', max_length=40),
        ),
    ]
