# Generated by Django 2.2 on 2019-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powiadomienia', '0004_auto_20190504_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powiadomienie',
            name='typPowiadomienia',
            field=models.CharField(choices=[('testowe', 'testowe'), ('1', 'rodzaj 1'), ('2', 'rodzaj 2')], default='testowe', max_length=40),
        ),
    ]
