# Generated by Django 2.2 on 2019-05-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powiadomienia', '0006_auto_20190504_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powiadomienie',
            name='typPowiadomienia',
            field=models.CharField(choices=[('testowe', 'testowe'), ('100', 'rodzaj 1'), ('2iuyg', 'rodzaj 2'), ('rrr', 'AAAAAaaaaAAAA')], default='testowe', max_length=40),
        ),
    ]
