# Generated by Django 2.2 on 2019-05-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powiadomienia', '0007_auto_20190504_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='powiadomienie',
            name='grupaOdbiorcow',
            field=models.CharField(choices=[('Wszyscy', 'wszyscy'), ('Politechnika', 'politechnika'), ('Uniwersytet', 'uniwersytet'), ('Pozostali', 'pozostali')], default='Wszyscy', max_length=40),
        ),
        migrations.AlterField(
            model_name='powiadomienie',
            name='typPowiadomienia',
            field=models.CharField(choices=[('testowe', 'testowe'), ('Przypomnienie o wydarzeniu', 'przypomnienie'), ('Ważne informacje', 'ważne'), ('Konkursy', 'konkurs')], default='testowe', max_length=40),
        ),
    ]
