# Generated by Django 2.2 on 2019-06-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powiadomienia', '0009_auto_20190504_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powiadomienie',
            name='kategoria',
            field=models.CharField(choices=[('testowe', 'testowe'), ('Przypomnienie o wydarzeniu', 'Przypomnienia'), ('Ważne informacje', 'Ważne'), ('Konkursy', 'Konkurs'), ('Inne', 'Inne')], default='testowe', max_length=40),
        ),
    ]
