# Generated by Django 2.2 on 2019-06-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powiadomienia', '0010_auto_20190603_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powiadomienie',
            name='odbiorcy',
            field=models.CharField(choices=[('wszyscy', 'Wszyscy'), ('Brak uczelni', 'Brak uczelni'), ('Politechnika Rzeszowska', 'Politechnika Rzeszowska'), ('Uniwersytet Rzeszowski', 'Uniwersytet Rzeszowski'), ('Inna uczelnia', 'Inna uczelnia')], default='Wszyscy', max_length=40),
        ),
    ]
