# Generated by Django 2.2 on 2019-04-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonogram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='koncert',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='koncert_pics'),
        ),
    ]
