# Generated by Django 2.2 on 2019-05-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonogram', '0003_auto_20190504_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koncert',
            name='tydzien',
            field=models.CharField(choices=[('TK', 'Tydzien Kultury'), ('TS', 'Tydzien Sportu'), ('KO', 'Koncerty')], default='KO', max_length=2),
        ),
    ]
