# Generated by Django 2.2 on 2019-06-05 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harmonogram', '0006_auto_20190604_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koncert',
            name='organizatorzy',
        ),
        migrations.AddField(
            model_name='koncert',
            name='organizator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
