# Generated by Django 2.2 on 2019-05-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biuro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='isLost',
            field=models.BooleanField(default=False),
        ),
    ]
