# Generated by Django 2.2 on 2019-05-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biuro', '0002_lostitem_islost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='gallery_pics/%Y/%m/%d/'),
        ),
    ]
