# Generated by Django 2.2 on 2019-05-23 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biuro', '0003_auto_20190523_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='acceptedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accepted_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
