# Generated by Django 2.2 on 2019-05-23 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biuro', '0005_auto_20190523_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='acceptedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accepted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
